package main

// 多语言支持
type lang struct {
	code string
	name string
}

var languages = []lang{
	{"zh", "中文"},
	{"en", "English"},
}

var translations = map[string]map[string]string{
	"zh": {
		"app_name":    "Queen",
		"author":      "kesonglab💗 · 由 yt-dlp 强力驱动 · 采用 Mole 风格",
		"menu_paste":  "粘贴链接下载",
		"menu_paste_d": "每行一个链接，Ctrl+D 开始",
		"menu_clip":   "从剪贴板读取",
		"menu_clip_d": "读取剪贴板中的链接",
		"menu_retry":  "重试失败链接",
		"menu_retry_d": "读取上次失败的链接",
		"menu_settings": "下载设置",
		"menu_settings_d": "播放列表/音频/字幕/目录等",
		"menu_opendir": "打开下载目录",
		"menu_opendir_d": "在 Finder 中打开",
		"menu_update": "更新 yt-dlp",
		"menu_update_d": "升级到最新版本",
		"menu_changelog": "更新日志",
		"menu_changelog_d": "查看本次更新内容",
		"menu_quit": "退出",
		"menu_quit_d": "再见",
		"menu_nav": "↑↓ 选择 · Enter 确认 · q 退出",
		"input_placeholder": "粘贴视频链接，每行一个，Ctrl+D 开始…",
		"input_url_hint": "Ctrl+D 开始下载 · Esc 返回 · 每行一个链接",
		"input_dir_hint": "输入绝对路径 · Ctrl+D 确认 · Esc 返回",
		"input_dir_placeholder": "输入新的下载目录（绝对路径），Ctrl+D 确认",
		"setting_playlist": "播放列表模式",
		"setting_audio": "音频模式 (mp3)",
		"setting_subs": "下载字幕",
		"setting_embed": "嵌入标题/封面",
		"setting_cookie": "Cookie 浏览器",
		"setting_retry": "每链接重试次数",
		"setting_concurrency": "并发下载数",
		"setting_dir": "下载目录",
		"setting_save": "保存并返回",
		"setting_lang": "语言 / Language",
		"setting_nav": "↑↓ 选择 · ←→ 切换 · Esc 保存并返回",
		"on": "开",
		"off": "关",
		"cookie_auto": "自动检测",
		"times": "次",
		"download_title": "下载结果",
		"download_success": "成功",
		"download_fail": "失败",
		"download_aborted": "已中止",
		"download_retry_file": "失败链接已保存到",
		"download_summary_nav": "Enter 返回菜单 · q 退出",
		"batch_progress": "批量进度",
		"batch_elapsed": "已用",
		"batch_eta": "预计还需",
		"batch_abort": "按 q 中止",
		"more_tasks": "还有 %d 个任务",
		"speed": "速度",
		"eta": "剩余",
		"waiting": "等待中",
		"eta_done": "完成",
		"updating_title": "更新 yt-dlp",
		"updating": "正在更新...",
		"update_ok": "更新完成",
		"update_brew": "请改用 brew upgrade yt-dlp",
		"update_nav": "Enter 返回菜单",
		"changelog_title": "更新日志 / Changelog",
		"changelog_nav": "↑↓ 滚动 · Esc 返回",
		"toast_no_urls": "没有有效的链接",
		"toast_clip_fail": "读取剪贴板失败",
		"toast_clip_ok": "已从剪贴板读取 %d 个链接",
		"toast_no_retry": "没有失败的链接记录",
		"toast_retry_ok": "读取 %d 个失败链接",
		"toast_open_fail": "打开目录失败",
		"toast_open_ok": "已打开",
		"toast_dir_empty": "目录为空，未修改",
		"toast_dir_fail": "创建目录失败",
		"toast_dir_ok": "下载目录已设为",
		"toast_done": "下载完成: 成功 %d, 失败 %d",
		"notify_done_title": "Queen 下载完成",
		"notify_done_ok": "全部成功，共 %d 个",
		"notify_done_fail": "完成 %d 个，失败 %d 个",
		"notify_fail_title": "Queen 下载失败",
		"dep_missing": "缺少依赖",
		"dep_install_q": "是否用 brew 安装缺失依赖？(y/n)",
		"dep_no_brew": "未找到 brew，请先安装: https://brew.sh",
		"dep_installed": "依赖检查通过",
		"dep_retry_hint": "请安装依赖后重试。",
		"dep_install_fail": "安装失败，请手动执行: brew install",
	},
	"en": {
		"app_name":    "Queen",
		"author":      "kesonglab💗 · Power by yt-dlp · Mole style",
		"menu_paste":  "Paste links to download",
		"menu_paste_d": "One link per line, Ctrl+D to start",
		"menu_clip":   "Read from clipboard",
		"menu_clip_d": "Load links from clipboard",
		"menu_retry":  "Retry failed links",
		"menu_retry_d": "Load previously failed links",
		"menu_settings": "Settings",
		"menu_settings_d": "Playlist/audio/subs/dir etc.",
		"menu_opendir": "Open download folder",
		"menu_opendir_d": "Reveal in Finder",
		"menu_update": "Update yt-dlp",
		"menu_update_d": "Upgrade to latest version",
		"menu_changelog": "Changelog",
		"menu_changelog_d": "See what's new in this release",
		"menu_quit": "Quit",
		"menu_quit_d": "Goodbye",
		"menu_nav": "↑↓ navigate · Enter confirm · q quit",
		"input_placeholder": "Paste video links, one per line, Ctrl+D to start…",
		"input_url_hint": "Ctrl+D to start · Esc back · one link per line",
		"input_dir_hint": "Enter absolute path · Ctrl+D confirm · Esc back",
		"input_dir_placeholder": "Enter new download folder (absolute path), Ctrl+D to confirm",
		"setting_playlist": "Playlist mode",
		"setting_audio": "Audio only (mp3)",
		"setting_subs": "Download subtitles",
		"setting_embed": "Embed title/thumbnail",
		"setting_cookie": "Cookie browser",
		"setting_retry": "Retries per link",
		"setting_concurrency": "Concurrent downloads",
		"setting_dir": "Download folder",
		"setting_save": "Save & back",
		"setting_lang": "Language / 语言",
		"setting_nav": "↑↓ navigate · ←→ toggle · Esc save & back",
		"on": "On",
		"off": "Off",
		"cookie_auto": "Auto detect",
		"times": "x",
		"download_title": "Download Results",
		"download_success": "OK",
		"download_fail": "Failed",
		"download_aborted": "Aborted",
		"download_retry_file": "Failed links saved to",
		"download_summary_nav": "Enter back to menu · q quit",
		"batch_progress": "Batch progress",
		"batch_elapsed": "elapsed",
		"batch_eta": "ETA",
		"batch_abort": "press q to abort",
		"more_tasks": "… %d more tasks",
		"speed": "speed",
		"eta": "ETA",
		"waiting": "queued",
		"eta_done": "Done",
		"updating_title": "Updating yt-dlp",
		"updating": "Updating...",
		"update_ok": "Update complete",
		"update_brew": "Run brew upgrade yt-dlp instead",
		"update_nav": "Enter back to menu",
		"changelog_title": "Changelog",
		"changelog_nav": "↑↓ scroll · Esc back",
		"toast_no_urls": "No valid links found",
		"toast_clip_fail": "Failed to read clipboard",
		"toast_clip_ok": "Loaded %d links from clipboard",
		"toast_no_retry": "No failed links recorded",
		"toast_retry_ok": "Loaded %d failed links",
		"toast_open_fail": "Failed to open folder",
		"toast_open_ok": "Opened",
		"toast_dir_empty": "Empty path, unchanged",
		"toast_dir_fail": "Failed to create folder",
		"toast_dir_ok": "Download folder set to",
		"toast_done": "Download done: %d OK, %d failed",
		"notify_done_title": "Queen Download Done",
		"notify_done_ok": "All %d succeeded",
		"notify_done_fail": "%d done, %d failed",
		"notify_fail_title": "Queen Download Failed",
		"dep_missing": "Missing dependencies",
		"dep_install_q": "Install missing dependencies with brew? (y/n)",
		"dep_no_brew": "brew not found, install it first: https://brew.sh",
		"dep_installed": "Dependency check passed",
		"dep_retry_hint": "Install the dependencies and try again.",
		"dep_install_fail": "Install failed, run manually: brew install",
	},
}

func tr(cfg *Config, key string) string {
	m := translations[cfg.Lang]
	if m == nil {
		m = translations["zh"]
	}
	if v, ok := m[key]; ok {
		return v
	}
	return key
}

func nextLang(cur string) string {
	for i, l := range languages {
		if l.code == cur {
			return languages[(i+1)%len(languages)].code
		}
	}
	return "zh"
}